version: '3'
services:
    web:
        container_name: lipasafe_help_center
        image: sodiumafrica/sodiumserver:1.0
        volumes:
            - ./docker/vhost.conf:/etc/nginx/servers/help.lipasafe.com.conf:rw
            - .:/var/www:rw
        ports:
          - 15013:80
