site_name: LipaSafe Help Center

pages:
    - Home: 'index.md'
    - Overview:
        - 'What is escrow?': 'overview/what-is-escrow.md'
        - 'How does LipaSafe work?': 'overview/how-it-works.md'

    - Accounts:
            - 'Signing up': 'accounts/signing-up.md'

theme:
    name: 'material'
    logo: 'images/logo.png'
    font:
        text: 'Work Sans'
        code: 'Ubuntu Mono'

    palette:
        primary: 'indigo'
        accent: 'light green'